# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(SRRG_SYSTEM_UTILS_LIBRARY_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(SRRG_SYSTEM_UTILS_LIBRARY_INCLUDE_DIRS)
   
set(SRRG_SYSTEM_UTILS_LIBRARY_LIBRARIES
  ${ROOT_DIR}/lib/libsrrg_system_utils_library.so
  CACHE STRING "" FORCE)

mark_as_advanced(SRRG_SYSTEM_UTILS_LIBRARY_LIBRARIES)
 
set(SRRG_SYSTEM_UTILS_LIBRARY_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_LIBRARY_DEPENDS "" CACHE INTERNAL "" FORCE)
 