# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(SYSTEM_UTILS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(SYSTEM_UTILS_INCLUDE_DIRS)
   
set(SYSTEM_UTILS_LIBRARIES
  ${ROOT_DIR}/lib/libsystem_utils.so
  CACHE STRING "" FORCE)

mark_as_advanced(SYSTEM_UTILS_LIBRARIES)
 
set(SYSTEM_UTILS_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(SYSTEM_UTILS_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 