# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(YAML_PARSER_LIBRARY_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(YAML_PARSER_LIBRARY_INCLUDE_DIRS)
   
set(YAML_PARSER_LIBRARY_LIBRARIES
  ${ROOT_DIR}/lib/libyaml_parser_library.so
  CACHE STRING "" FORCE)

mark_as_advanced(YAML_PARSER_LIBRARY_LIBRARIES)
 
set(YAML_PARSER_LIBRARY_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(YAML_PARSER_LIBRARY_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 