# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(PNP_INCLUDE_DIRS "/home/marc/workspace/SPQReL/worktree/PetriNetPlans/PNPnaoqi;/home/marc/workspace/SPQReL/worktree/PetriNetPlans/PNPnaoqi/../PNP/include;/home/marc/workspace/SPQReL/worktree/PetriNetPlans/PNPnaoqi/include;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/xml2/include;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/xml2/include/libxml2;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/share/cmake/toolchain/linux64_cross_x86/../../../../i686-aldebaran-linux-gnu/sysroot/usr/include;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/zlib/include;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/xz_utils/include" CACHE INTERNAL "" FORCE)
 
set(PNP_LIBRARIES "general;/home/marc/workspace/SPQReL/worktree/PetriNetPlans/PNPnaoqi/build-pepper/sdk/lib/libpnp.so" CACHE INTERNAL "" FORCE)
 
set(PNP_TARGET "pnp" CACHE INTERNAL "" FORCE)

set(PNP_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(PNP_DEPENDS "XML2;DL;ZLIB;XZ_UTILS;PTHREAD" CACHE INTERNAL "" FORCE)
 