# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(SRRG_PATH_MAP_LIBRARY_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(SRRG_PATH_MAP_LIBRARY_INCLUDE_DIRS)
   
set(SRRG_PATH_MAP_LIBRARY_LIBRARIES
  ${ROOT_DIR}/lib/libsrrg_path_map_library.so
  CACHE STRING "" FORCE)

mark_as_advanced(SRRG_PATH_MAP_LIBRARY_LIBRARIES)
 
set(SRRG_PATH_MAP_LIBRARY_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(SRRG_PATH_MAP_LIBRARY_DEPENDS "OPENCV2_CORE;ZLIB;TBB;DL;PTHREAD;RT;EIGEN3" CACHE INTERNAL "" FORCE)
 