# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(NAOQI_SENSOR_UTILS_LIBRARY_INCLUDE_DIRS "/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/naoqi_sensor_utils;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/opt/naoqi-sdk-2.5.5.5-linux64/include/boost;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include" CACHE INTERNAL "" FORCE)
 
set(NAOQI_SENSOR_UTILS_LIBRARY_LIBRARIES "general;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/build-sysinstall/sdk/lib/libnaoqi_sensor_utils_library.so" CACHE INTERNAL "" FORCE)
 
set(NAOQI_SENSOR_UTILS_LIBRARY_TARGET "naoqi_sensor_utils_library" CACHE INTERNAL "" FORCE)

set(NAOQI_SENSOR_UTILS_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(NAOQI_SENSOR_UTILS_LIBRARY_DEPENDS "EIGEN3;ALPROXIES;ALCOMMON;BOOST_SIGNALS;RTTOOLS;ALVALUE;ALERROR;QI;BOOST;BOOST_ATOMIC;BOOST_DATE_TIME;BOOST_CHRONO;BOOST_FILESYSTEM;BOOST_SYSTEM;BOOST_REGEX;BOOST_PROGRAM_OPTIONS;OPENSSL;BOOST_LOCALE;BOOST_THREAD;ICU;PTHREAD;DL;RT;OPENCV2_CORE;ZLIB" CACHE INTERNAL "" FORCE)
 