# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_LOCALIZER2D_LIBRARY_INCLUDE_DIRS "/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/opt/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/naoqi-sdk-2.5.5.5-linux64/include" CACHE INTERNAL "" FORCE)
 
set(SRRG_LOCALIZER2D_LIBRARY_LIBRARIES "general;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/build-sysinstall/sdk/lib/libsrrg_localizer2d_library.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_LOCALIZER2D_LIBRARY_TARGET "srrg_localizer2d_library" CACHE INTERNAL "" FORCE)

set(SRRG_LOCALIZER2D_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_LOCALIZER2D_LIBRARY_DEPENDS "SRRG_PATH_MAP_LIBRARY;EIGEN3;OPENCV2_IMGPROC;OPENCV2_CORE;ZLIB" CACHE INTERNAL "" FORCE)
 