# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_PATH_MAP_LIBRARY_INCLUDE_DIRS "/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/home/marc/workspace/SPQReL/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/home/marc/workspace/SPQReL/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/home/marc/workspace/SPQReL/naoqi-sdk-2.5.5.5-linux64/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(SRRG_PATH_MAP_LIBRARY_LIBRARIES "general;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/build-linux64/sdk/lib/libsrrg_path_map_library.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_PATH_MAP_LIBRARY_TARGET "srrg_path_map_library" CACHE INTERNAL "" FORCE)

set(SRRG_PATH_MAP_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_PATH_MAP_LIBRARY_DEPENDS "OPENCV2_CORE;ZLIB;EIGEN3" CACHE INTERNAL "" FORCE)
 