# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_SYSTEM_UTILS_YAML_INCLUDE_DIRS "/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_YAML_LIBRARIES "general;/home/iocchi/src/spqrel_navigation/build-linux64/sdk/lib/libsrrg_system_utils_yaml.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_YAML_TARGET "srrg_system_utils_yaml" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_YAML_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_YAML_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 