# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(NAOQI_LOCALIZER_LIBRARY_INCLUDE_DIRS "/home/iocchi/src/spqrel_navigation/naoqi/naoqi_localizer;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/home/iocchi/src/spqrel_navigation/naoqi/naoqi_sensor_utils;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/boost;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include" CACHE INTERNAL "" FORCE)
 
set(NAOQI_LOCALIZER_LIBRARY_LIBRARIES "general;/home/iocchi/src/spqrel_navigation/naoqi/build-linux64/sdk/lib/libnaoqi_localizer_library.so" CACHE INTERNAL "" FORCE)
 
set(NAOQI_LOCALIZER_LIBRARY_TARGET "naoqi_localizer_library" CACHE INTERNAL "" FORCE)

set(NAOQI_LOCALIZER_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(NAOQI_LOCALIZER_LIBRARY_DEPENDS "SRRG_SYSTEM_UTILS_YAML;SRRG_LOCALIZER2D_LIBRARY;SRRG_PATH_MAP_LIBRARY;NAOQI_SENSOR_UTILS_LIBRARY;EIGEN3;ALPROXIES;ALCOMMON;BOOST_SIGNALS;RTTOOLS;ALVALUE;ALERROR;QI;BOOST;BOOST_ATOMIC;BOOST_DATE_TIME;BOOST_CHRONO;BOOST_FILESYSTEM;BOOST_SYSTEM;BOOST_REGEX;BOOST_PROGRAM_OPTIONS;OPENSSL;BOOST_LOCALE;BOOST_THREAD;ICU;PTHREAD;DL;RT;OPENCV2_HIGHGUI;OPENCV2_IMGPROC;OPENCV2_CORE;ZLIB" CACHE INTERNAL "" FORCE)
 