# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_SYSTEM_UTILS_LIBRARY_INCLUDE_DIRS "/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_LIBRARY_LIBRARIES "general;/home/iocchi/src/spqrel_navigation/naoqi/build-linux64/sdk/lib/libsrrg_system_utils_library.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_LIBRARY_TARGET "srrg_system_utils_library" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_LIBRARY_DEPENDS "" CACHE INTERNAL "" FORCE)
 