# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SYSTEM_UTILS_INCLUDE_DIRS "/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(SYSTEM_UTILS_LIBRARIES "general;/home/iocchi/src/spqrel_navigation/naoqi/build-linux64/sdk/lib/libsystem_utils.so" CACHE INTERNAL "" FORCE)
 
set(SYSTEM_UTILS_TARGET "system_utils" CACHE INTERNAL "" FORCE)

set(SYSTEM_UTILS_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SYSTEM_UTILS_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 