# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(YAML_PARSER_LIBRARY_INCLUDE_DIRS "/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/home/iocchi/src/spqrel_navigation/naoqi;/home/iocchi/src/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/usr/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include;/opt/Aldebaran/naoqi/naoqi-sdk-2.5.5.5-linux64/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(YAML_PARSER_LIBRARY_LIBRARIES "general;/home/iocchi/src/spqrel_navigation/naoqi/build-linux64/sdk/lib/libyaml_parser_library.so" CACHE INTERNAL "" FORCE)
 
set(YAML_PARSER_LIBRARY_TARGET "yaml_parser_library" CACHE INTERNAL "" FORCE)

set(YAML_PARSER_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(YAML_PARSER_LIBRARY_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 