# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_PATH_MAP_LIBRARY_INCLUDE_DIRS "/home/iocchi/src/SPQREL/qi_ws/spqrel_navigation/naoqi;/home/iocchi/src/SPQREL/qi_ws/spqrel_navigation/naoqi/../src;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/eigen3/include/eigen3;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/opencv2/include;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/zlib/include;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/tbb/include;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/share/cmake/toolchain/linux64_cross_x86/../../../../i686-aldebaran-linux-gnu/sysroot/usr/include;/opt/Aldebaran/naoqi/ctc-linux64-atom-2.5.2.74/eigen3/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(SRRG_PATH_MAP_LIBRARY_LIBRARIES "general;/home/iocchi/src/SPQREL/qi_ws/spqrel_navigation/build-pepper/sdk/lib/libsrrg_path_map_library.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_PATH_MAP_LIBRARY_TARGET "srrg_path_map_library" CACHE INTERNAL "" FORCE)

set(SRRG_PATH_MAP_LIBRARY_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_PATH_MAP_LIBRARY_DEPENDS "OPENCV2_CORE;ZLIB;TBB;DL;PTHREAD;RT;EIGEN3" CACHE INTERNAL "" FORCE)
 