# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(SRRG_SYSTEM_UTILS_YAML_INCLUDE_DIRS "/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/naoqi/../src;/home/marc/workspace/SPQReL/ctc-linux64-atom-2.5.2.74/eigen3/include/eigen3" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_YAML_LIBRARIES "general;/home/marc/workspace/SPQReL/worktree/spqrel_navigation/build-pepper/sdk/lib/libsrrg_system_utils_yaml.so" CACHE INTERNAL "" FORCE)
 
set(SRRG_SYSTEM_UTILS_YAML_TARGET "srrg_system_utils_yaml" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_YAML_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(SRRG_SYSTEM_UTILS_YAML_DEPENDS "EIGEN3" CACHE INTERNAL "" FORCE)
 